#
# Ability to override the name
# overrideName: 
# overrideFullName: 

# Values belonging to delivery database
app:
  # Name of the application
  name: delivery-db
  imageTag: "1.0.0"
  image: "delivery-db"
  imageRegistry: "localhost:5000"
  imagePullPolicy: "Always"
  replicas: 1
  env:
    - name: POSTGRES_USER
      value: delivery-service
    - name: POSTGRES_PASSWORD
      value: delivery-password
    - name: POSTGRES_DB
      value: delivery
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
  service:
    serviceType: ClusterIP
    internalPort: 5432
  volumeMount:
    mountPath: /var/lib/postgresql/data/pgdata
