INSERT INTO ADDRESSES (ID, RECIPIENT, STREET, HOUSE_NUMBER, CITY) VALUES ('0815', 'Max Mustermann', 'Poststr.', '1', '26122 Oldenburg');
INSERT INTO ADDRESSES (ID, RECIPIENT, STREET, HOUSE_NUMBER, CITY) VALUES ('0816', 'Erika Mustermann', 'II. Hagen', '7', '45127 Essen');
